config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources:posts do
    resources :comments
  end
  
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, length:{minimum: 3,
    message:"三文字以上書いてください"}
    validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
     @post = Post.find(params[:post_id])
     @post.comments.create(comment_params)
     redirect_to post_path(@post)
    end
    
    def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
    end
    
    private
     def comment_params
        params.require(:comment).permit(:body)
     end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
     @posts = Post.all.order(created_at:'desc')
    end
    
    def new
     @post = Post.new
    end
    
    def create
    #render plain:params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
     flash[:notice]="投稿しました"
       redirect_to "/"
    else
    render 'new'
    end
    end
    
    def show
    @post = Post.find(params[:id])
    end
    
    def edit
    @post = Post.find(params[:id])
    end
    
    def update
     @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice]="編集しました"
       redirect_to "/"
    else
    render 'edit'
    end
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to "/"
    end
    
 private
    def post_params
     params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pet</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="content-type" content="text/html" charset = "utf-8">
    <!-- fontawesome -->
 <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
　　　<!-- end -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <div class="header-title">落とし物リスト<i class="fas fa-wallet"></i></div>
    <div class= "header-right">
    <%= link_to "トップへ", root_path %>
    <%= link_to "新規投稿", new_post_path %>
    </div>
    </header>
    <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class=main>
    <%= yield %>
    </div>
    <footer>
      <p class="copyright">copyright © PENGIN Co. All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<p>
<%= f.text_field :title, placeholder: 'お名前' %>
<% if @post.errors.messages[:title].any? %>
<span class="error"><%= @post.errors.messages[:title][0]%></span>
<% end %>
</p>
<p>
<%= f.text_area :body, placeholder: '内容' %>
<% if @post.errors.messages[:body].any? %>
<span class="error"><%= @post.errors.messages[:body][0]%></span>
<% end %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/posts/edit.html.erb
<div class="post">
<h2>編集画面</h2>
<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="contain">
<% @posts.each do |post| %>
<div class="article">
<%= link_to post.title, post_path(post), class:"caption" %>
<div class="func">
<%= link_to '[編集]', edit_post_path(post), class:"edit" %>
<%= link_to '[削除]', post_path(post),
method: :delete, class:"destroy",data:{confirm: '削除しても大丈夫ですか？'} %>
</div>
</div>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="post">
<h2>新規投稿</h2>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="sub">
<h2 class="w">お名前</h2>
<p><%= @post.title %></p>
 <h2 class="w">内容</h2>
<p><%= @post.body %></p>
</div>

<div class="sub">
<h3>コメント</h3>
<% if @post.comments.any? %>
 <ul>
    <% @post.comments.each do |comment| %>
  <li>
      <%= comment.body %>
      <%= link_to '[×]', post_comment_path(@post,comment), method: :delete ,
 class: 'destroy_1', data: {confirm: '削除してもよろしいでしょうか？'}%>
  </li>
    <% end %>
 </ul>
<% end %>
<%= form_for ([@post, @post.comments.build ])  do |f| %>

<p>
<%= f.text_field :body %>
</p>

<p>
<%= f.submit %>
</p>
<% end %>
</div>